sudo: required
language: rust

# Cache cargo symbols for faster build
cache: cargo

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake # also required for cargo-update
    sources:
      - kalakris-cmake

# Run builds for all the trains
rust:
  - nightly
  - beta
  - stable

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-update || echo "cargo-update already installed"
  - cargo install cargo-travis || echo "cargo-travis already installed"
  - cargo install-update -a # Update outdated cached binaries

# Build Script
script:
  - |
      cargo build &&
      cargo test &&
      cargo bench &&
      cargo doc --verbose

after_success:
  # Measure code coverage and upload to coveralls.io
  - cargo coveralls
  # Upload documentation to github.io (gh-pages branch)
  - cargo doc-upload --path "$TRAVIS_BRANCH"

# Do not notify
notifications:
  email:
    on_success: never

# Build environment
env:
  global:
    # Encrypted GitHub token for documentation
    - secure: DT1ng1fpr4aVrA/+qASPQ2qB3lg4d+HcDmrlozkr+zmu4OjEOBgK7+3zb3IYiR9Le7z5Zs0YxqxJIRfhIXhcAMF9C8uX1qJ0h3oCVG7qfP6HRvWLmTd+OVS1zAzZXrN6AXg0Qu3m3FEgVOMsancH2n3a55XKK+PE4lGcEGugO/js/rVg7QMAAamzLPUW+PfqJz5yzHFjpcKkcocF/5+N8Yz+28XzH4We8Uep9GHL+RdyKsZg8p4AVSre/X9g43aqB9O4ZYGYii2n3PJpTfZ2PDOI1LZvY647c70s3VxBv+ZeX5PS1qCdHtXdUhHAGv8LuSC82/NduS36fyDvFHsJtZg9fEGwFdsNQQeAJwmHHrbEbFzHL5oY9VgmjDBE7EU7gw36DSOeJq7HzKL206CYFjuZDQkBQjQP7O1biH8kxNU41GdiJYD79mrjnTw1lADRqISMOgehEjGE3mm8M6Ya3N18SOs+c1smkJGUK89Sjs/SNo9xdf6fEQmYPBs2HlneiVL+ikWa+Mp7PHRClKOb2gkh0nmylEOGs9cpqMj4cNVGgKUi7+eqpJHa1GDYkVCdoG1VM0K8hv7EwZkkmVa660t7FIn+jE1K+YO26s/xqkZ5ei7AhEiA6ZessxLOCLJ7I/scSVG3OG1BEztj7K9G2jujqpQOSQUeYpfK29QCdUA=
