sudo: false
language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only stable doc
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
after_success:
- travis-cargo --only stable doc-upload
- travis-cargo coveralls --no-sudo
notifications:
  email:
    on_success: never
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=dev
  - secure: FkXTHSuXuea9GzyjaUEhKB/1BPCT0+2l+C/k03Ju3yRVjRGeLPbe2rhRgCx/VD1fYcrDIDAZcvw6iFzcjzhMdJha6Mybk50udT4uUmFzgfo0T7USEPHVXEc1whLOnAoYkza/IAAbVbIovnnAT55i79o86Ao+X50Q1AHFSgu82/IoAwhCdrosrLbfhDTorpBSSjqHPba7StXyceupSrAFcJBbpiHLaHECP2aIiJSc1oBe/7WDXzrHrKw1mxoKFWgmSQrlkA2b2ph1K3gXdlzMelQUesG5gTUlUEiLHXIGToDfFUUS813x5cBaPJ0R+VwSdiQRZ7O1HOvlf0iicm5LGQPtvQMI89jm31rBGzhF3vSwhhyeyiA30ACg9sZtcvI5xB6HVrFtlKVE6Z/WJhLj18qksYBpsftFzla8U4erWW6XDeVW31aRY/8pUJSQInnVvGbVM9TY5F2T/SIJ+11WZTXuhoBVgk35mAzMrucZ1UrXZjxeoOF5oHYWK0D+udIkyvRI/G80I7potyxr3f5VFPsdaTx+NTLO+1VOMVYahJwl+/RfA4n0+4/1p5BtnspyArx8oKtu25vpFs/kBowvHiw/B9JPTygKgqOvDytY6H9wMsDEbjsWtDZUZnRt4pfK99Ol/HHceuvtuO0Pyl9MS3Yp+68d7qwjSnX/EfyQl1E=
